from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
from pathlib import Path
from typing import Protocol

from alicebot_api.vnext_event_log import append_event
from alicebot_api.vnext_repositories import JsonObject

DEFAULT_VNEXT_ARTIFACT_EXPORT_ROOT = Path("/tmp/alicebot-vnext-artifact-exports")


class VNextQueueValidationError(ValueError):
    """Raised when a vNext queue or artifact operation is invalid."""


class VNextQueueNotFoundError(VNextQueueValidationError):
    """Raised when a vNext queue artifact or task cannot be found."""


class VNextQueueStore(Protocol):
    def append_event(self, event: JsonObject) -> JsonObject: ...

    def create_task(self, task: JsonObject, *, actor_type: str = "system") -> JsonObject: ...

    def claim_next_task(self) -> JsonObject | None: ...

    def update_task_status(self, *, task_id: str, status: str, details: JsonObject | None = None) -> JsonObject: ...

    def create_artifact(self, artifact: JsonObject) -> JsonObject: ...

    def get_artifact(self, artifact_id: str) -> JsonObject | None: ...

    def update_artifact_status(self, *, artifact_id: str, status: str) -> JsonObject: ...


@dataclass(frozen=True, slots=True)
class QueueTaskRequest:
    title: str
    task_type: str
    instructions: str
    requested_by: str = "user"
    scope_json: JsonObject = field(default_factory=dict)
    allowed_sources_json: list[object] = field(default_factory=list)
    domain: str = "unknown"
    sensitivity: str = "unknown"
    write_policy: str = "proposal_only"
    scheduled_for: str | None = None
    metadata_json: JsonObject = field(default_factory=dict)
    actor_type: str = "system"
    actor_id: str | None = None
    trace_id: str | None = None
    run_id: str | None = None
    agent_identity: JsonObject | None = None
    policy_decision: JsonObject | None = None


@dataclass(frozen=True, slots=True)
class QueueProcessResult:
    status: str
    task_id: str | None = None
    artifact_id: str | None = None
    error_message: str | None = None

    def to_record(self) -> JsonObject:
        return {
            "status": self.status,
            "task_id": self.task_id,
            "artifact_id": self.artifact_id,
            "error_message": self.error_message,
        }


def _normalize_required_text(value: str, *, field_name: str) -> str:
    normalized = " ".join(value.split()).strip()
    if normalized == "":
        raise VNextQueueValidationError(f"{field_name} must not be empty")
    return normalized


def _artifact_type_for_task(task_type: str) -> str:
    if task_type == "draft":
        return "draft"
    if task_type == "create_context_pack":
        return "context_pack"
    if task_type in {"research", "analyze", "compare", "summarize"}:
        return "research_brief"
    return "queue_result"


def _artifact_status_for_policy(write_policy: str) -> str:
    if write_policy == "auto_generate_artifact":
        return "reviewed"
    return "draft"


def _artifact_markdown_for_task(task: JsonObject) -> str:
    title = str(task.get("title", "Queue Task"))
    instructions = str(task.get("instructions", "")).strip()
    task_type = str(task.get("task_type", "synthesize"))
    scope_json = task.get("scope_json") if isinstance(task.get("scope_json"), dict) else {}
    allowed_sources = task.get("allowed_sources_json") if isinstance(task.get("allowed_sources_json"), list) else []
    return "\n".join(
        [
            f"# {title}",
            "",
            f"Task type: {task_type}",
            "",
            "## Instructions",
            instructions or "No instructions were provided.",
            "",
            "## Scope",
            str(scope_json),
            "",
            "## Allowed Sources",
            str(allowed_sources),
            "",
            "## Result",
            "This deterministic vNext artifact was generated by the local queue worker scaffold.",
            "",
        ]
    )


class VNextQueueService:
    def __init__(self, store: VNextQueueStore) -> None:
        self.store = store

    def enqueue_task(self, request: QueueTaskRequest) -> JsonObject:
        title = _normalize_required_text(request.title, field_name="title")
        task_type = _normalize_required_text(request.task_type, field_name="task_type")
        instructions = _normalize_required_text(request.instructions, field_name="instructions")
        task = self.store.create_task(
            {
                "title": title,
                "task_type": task_type,
                "instructions": instructions,
                "requested_by": request.requested_by,
                "scope_json": request.scope_json,
                "allowed_sources_json": request.allowed_sources_json,
                "domain": request.domain,
                "sensitivity": request.sensitivity,
                "write_policy": request.write_policy,
                "scheduled_for": request.scheduled_for,
                "metadata_json": {
                    **request.metadata_json,
                    "agent_identity": request.agent_identity,
                    "agent_id": request.actor_id if request.actor_type == "agent" else None,
                    "policy_decision": request.policy_decision,
                    "trace_id": request.trace_id,
                },
            },
            actor_type=request.actor_type,
        )
        append_event(
            self.store,
            event_type="queue.task_enqueued",
            actor_type=request.actor_type,
            actor_id=request.actor_id,
            target_type="task",
            target_id=str(task["id"]),
            trace_id=request.trace_id,
            run_id=request.run_id,
            payload={"task_type": task_type, "write_policy": request.write_policy},
        )
        if request.actor_type == "agent" and request.actor_id is not None:
            append_event(
                self.store,
                event_type="agent.task_created",
                actor_type="agent",
                actor_id=request.actor_id,
                target_type="task",
                target_id=str(task["id"]),
                trace_id=request.trace_id,
                run_id=request.run_id,
                payload={"task_type": task_type, "agent_identity": request.agent_identity},
            )
        return task

    def process_next_task(self) -> QueueProcessResult:
        task = self.store.claim_next_task()
        if task is None:
            append_event(
                self.store,
                event_type="queue.worker_idle",
                actor_type="system",
                target_type="task_queue",
                payload={"status": "idle"},
            )
            return QueueProcessResult(status="idle")

        task_id = str(task["id"])
        try:
            artifact = self.store.create_artifact(
                {
                    "artifact_type": _artifact_type_for_task(str(task.get("task_type", "synthesize"))),
                    "title": str(task.get("title", "Queue Result")),
                    "content_markdown": _artifact_markdown_for_task(task),
                    "status": _artifact_status_for_policy(str(task.get("write_policy", "proposal_only"))),
                    "domain": str(task.get("domain", "unknown")),
                    "sensitivity": str(task.get("sensitivity", "unknown")),
                    "generated_by": "vnext_queue_worker",
                    "metadata_json": {
                        "task_id": task_id,
                        "task_type": task.get("task_type"),
                    },
                }
            )
            artifact_id = str(artifact["id"])
            self.store.update_task_status(
                task_id=task_id,
                status="completed",
                details={
                    "output_artifact_id": artifact_id,
                    "metadata_json": {"artifact_id": artifact_id},
                },
            )
            append_event(
                self.store,
                event_type="queue.task_completed",
                actor_type="system",
                target_type="task",
                target_id=task_id,
                payload={"artifact_id": artifact_id},
            )
            return QueueProcessResult(status="completed", task_id=task_id, artifact_id=artifact_id)
        except Exception as exc:
            self.store.update_task_status(
                task_id=task_id,
                status="failed",
                details={"error_message": str(exc)},
            )
            append_event(
                self.store,
                event_type="queue.task_failed",
                actor_type="system",
                target_type="task",
                target_id=task_id,
                payload={"error_type": type(exc).__name__, "error_message": str(exc)},
            )
            return QueueProcessResult(status="failed", task_id=task_id, error_message=str(exc))

    def review_artifact(self, *, artifact_id: str, action: str) -> JsonObject:
        action_to_status = {
            "review": "reviewed",
            "accept": "accepted",
            "reject": "rejected",
            "promote": "promoted_to_memory",
            "archive": "archived",
        }
        status = action_to_status.get(action)
        if status is None:
            raise VNextQueueValidationError("artifact review action must be review, accept, reject, promote, or archive")
        if self.store.get_artifact(artifact_id) is None:
            raise VNextQueueNotFoundError(f"artifact {artifact_id} was not found")
        artifact = self.store.update_artifact_status(artifact_id=artifact_id, status=status)
        append_event(
            self.store,
            event_type="artifact.reviewed",
            actor_type="system",
            target_type="artifact",
            target_id=artifact_id,
            payload={"action": action, "status": status},
        )
        return artifact

    def export_artifact_markdown(self, *, artifact_id: str, output_dir: str | Path) -> Path:
        artifact = self.store.get_artifact(artifact_id)
        if artifact is None:
            raise VNextQueueNotFoundError(f"artifact {artifact_id} was not found")
        content = str(artifact.get("content_markdown", ""))
        requested_output_dir = str(output_dir)
        target_dir = DEFAULT_VNEXT_ARTIFACT_EXPORT_ROOT.resolve()
        target_dir.mkdir(parents=True, exist_ok=True)
        artifact_digest = hashlib.sha256(artifact_id.encode("utf-8")).hexdigest()[:24]
        output_path = target_dir / f"artifact-{artifact_digest}.md"
        output_path.write_text(content, encoding="utf-8")
        append_event(
            self.store,
            event_type="artifact.exported",
            actor_type="system",
            target_type="artifact",
            target_id=artifact_id,
            payload={"output_path": str(output_path), "requested_output_dir": requested_output_dir},
        )
        return output_path


__all__ = [
    "DEFAULT_VNEXT_ARTIFACT_EXPORT_ROOT",
    "QueueProcessResult",
    "QueueTaskRequest",
    "VNextQueueNotFoundError",
    "VNextQueueService",
    "VNextQueueStore",
    "VNextQueueValidationError",
]
