export const REMOVED_WEB_FILES = [
  "app/admin/page.test.tsx",
  "app/admin/page.tsx",
  "app/chat/loading.tsx",
  "app/chat/page.test.tsx",
  "app/chat/page.tsx",
  "app/chief-of-staff/page.test.tsx",
  "app/chief-of-staff/page.tsx",
  "app/onboarding/page.test.tsx",
  "app/onboarding/page.tsx",
  "app/settings/page.test.tsx",
  "app/settings/page.tsx",
  "components/chief-of-staff-action-handoff-panel.test.tsx",
  "components/chief-of-staff-action-handoff-panel.tsx",
  "components/chief-of-staff-execution-routing-panel.test.tsx",
  "components/chief-of-staff-execution-routing-panel.tsx",
  "components/chief-of-staff-follow-through-panel.test.tsx",
  "components/chief-of-staff-follow-through-panel.tsx",
  "components/chief-of-staff-handoff-queue-panel.test.tsx",
  "components/chief-of-staff-handoff-queue-panel.tsx",
  "components/chief-of-staff-outcome-learning-panel.test.tsx",
  "components/chief-of-staff-outcome-learning-panel.tsx",
  "components/chief-of-staff-preparation-panel.test.tsx",
  "components/chief-of-staff-preparation-panel.tsx",
  "components/chief-of-staff-priority-panel.test.tsx",
  "components/chief-of-staff-priority-panel.tsx",
  "components/chief-of-staff-weekly-review-panel.test.tsx",
  "components/chief-of-staff-weekly-review-panel.tsx",
  "components/hosted-admin-panel.test.tsx",
  "components/hosted-admin-panel.tsx",
  "components/hosted-onboarding-panel.tsx",
  "components/hosted-settings-panel.test.tsx",
  "components/hosted-settings-panel.tsx",
  "components/mode-toggle.tsx",
  "components/request-composer.test.tsx",
  "components/request-composer.tsx",
  "components/response-composer.test.tsx",
  "components/response-composer.tsx",
  "components/response-history.test.tsx",
  "components/response-history.tsx",
  "components/thread-create.test.tsx",
  "components/thread-create.tsx",
  "components/thread-event-list.test.tsx",
  "components/thread-event-list.tsx",
  "components/thread-list.test.tsx",
  "components/thread-list.tsx",
  "components/thread-summary.test.tsx",
  "components/thread-summary.tsx",
  "components/thread-trace-panel.test.tsx",
  "components/thread-trace-panel.tsx",
  "components/thread-workflow-panel.test.tsx",
  "components/thread-workflow-panel.tsx",
] as const;

export const RETAINED_WEB_ROUTES = [
  "/",
  "/vnext",
  "/artifacts",
  "/memories",
  "/continuity",
  "/entities",
  "/traces",
] as const;

export const LEGACY_WEB_ROUTES = [
  "/approvals",
  "/tasks",
  "/gmail",
  "/calendar",
] as const;

export const REMOVED_API_CLIENT_MARKERS = [
  "/v0/responses",
  "/v0/chief-of-staff",
  "ChiefOfStaff",
  "submitAssistantResponse",
  "submitApprovalRequest",
  "getThreadResumptionBrief",
  "getTaskWorkspaceDetail",
] as const;

export const REMOVED_FIXTURE_MARKERS = [
  "threadFixtures",
  "agentProfileFixtures",
  "threadSessionFixtures",
  "threadEventFixtures",
  "requestHistoryFixtures",
  "responseHistoryFixtures",
  "buildFixtureRequestEntry",
  "buildFixtureResponseEntry",
  "buildFixtureThread",
] as const;
