#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

fail() {
  printf '[alice-api-dev] ERROR: %s\n' "$*" >&2
  exit 1
}

PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"
if [ ! -x "${PYTHON_BIN}" ]; then
  fail "Missing ${PYTHON_BIN}. Run 'make setup' before starting Alice."
fi

if [ -f "${REPO_ROOT}/.env" ]; then
  "${REPO_ROOT}/scripts/validate_env.sh" "${REPO_ROOT}/.env"
  PRESERVE_ENV_KEYS=(
    APP_ENV
    APP_HOST
    APP_PORT
    APP_RELOAD
    APP_LOG_MODE
    APP_LOG_LEVEL
    APP_LOG_PATH
    APP_LOG_MAX_BYTES
    APP_LOG_BACKUP_COUNT
    APP_ACCESS_LOG
    AUTH_SESSION_TTL_SECONDS
    CALENDAR_SECRET_MANAGER_URL
    CORS_ALLOWED_HEADERS
    CORS_ALLOWED_METHODS
    CORS_ALLOWED_ORIGINS
    CORS_ALLOW_CREDENTIALS
    CORS_PREFLIGHT_MAX_AGE_SECONDS
    DATABASE_URL
    DATABASE_ADMIN_URL
    DEVICE_LINK_TTL_SECONDS
    ENTRYPOINT_RATE_LIMIT_BACKEND
    GMAIL_SECRET_MANAGER_URL
    HEALTHCHECK_TIMEOUT_SECONDS
    HOSTED_ABUSE_BLOCK_THRESHOLD
    HOSTED_ABUSE_CONTROLS_ENABLED_BY_DEFAULT
    HOSTED_ABUSE_WINDOW_SECONDS
    HOSTED_CHAT_RATE_LIMIT_MAX_REQUESTS
    HOSTED_CHAT_RATE_LIMIT_WINDOW_SECONDS
    HOSTED_RATE_LIMITS_ENABLED_BY_DEFAULT
    HOSTED_SCHEDULER_RATE_LIMIT_MAX_REQUESTS
    HOSTED_SCHEDULER_RATE_LIMIT_WINDOW_SECONDS
    LEGACY_V0_ENABLED_OUTSIDE_DEV
    MAGIC_LINK_START_RATE_LIMIT_MAX_REQUESTS
    MAGIC_LINK_START_RATE_LIMIT_WINDOW_SECONDS
    MAGIC_LINK_TTL_SECONDS
    MAGIC_LINK_VERIFY_RATE_LIMIT_MAX_REQUESTS
    MAGIC_LINK_VERIFY_RATE_LIMIT_WINDOW_SECONDS
    MODEL_API_KEY
    MODEL_BASE_URL
    MODEL_NAME
    MODEL_PROVIDER
    MODEL_TIMEOUT_SECONDS
    PROVIDER_SECRET_MANAGER_URL
    REDIS_URL
    RESPONSE_RATE_LIMIT_WINDOW_SECONDS
    RESPONSE_RATE_LIMIT_MAX_REQUESTS
    RETRIEVAL_TRACE_RETENTION_DAYS
    S3_ENDPOINT_URL
    S3_ACCESS_KEY
    S3_SECRET_KEY
    S3_BUCKET
    SECURITY_HEADERS_ENABLED
    SECURITY_HEADERS_HSTS_INCLUDE_SUBDOMAINS
    SECURITY_HEADERS_HSTS_MAX_AGE_SECONDS
    TASK_WORKSPACE_ROOT
    ALICEBOT_AUTH_USER_ID
    PUBLIC_SAMPLE_DATA_PATH
    TELEGRAM_BOT_TOKEN
    TELEGRAM_BOT_USERNAME
    TELEGRAM_LINK_TTL_SECONDS
    TELEGRAM_WEBHOOK_RATE_LIMIT_MAX_REQUESTS
    TELEGRAM_WEBHOOK_RATE_LIMIT_WINDOW_SECONDS
    TELEGRAM_WEBHOOK_SECRET
    TRUSTED_PROXY_IPS
    TRUST_PROXY_HEADERS
    WORKSPACE_PROVIDER_CONFIGS_JSON
  )

  for key in "${PRESERVE_ENV_KEYS[@]}"; do
    if [ "${!key+x}" = "x" ]; then
      export "__PRESERVE_${key}=${!key}"
    fi
  done

  set -a
  . "${REPO_ROOT}/.env"
  set +a

  for key in "${PRESERVE_ENV_KEYS[@]}"; do
    preserve_key="__PRESERVE_${key}"
    if [ "${!preserve_key+x}" = "x" ]; then
      export "${key}=${!preserve_key}"
      unset "${preserve_key}"
    fi
  done
fi

cd "${REPO_ROOT}"

export APP_LOG_MODE="${APP_LOG_MODE:-stdout}"
export APP_ACCESS_LOG="${APP_ACCESS_LOG:-false}"
if [ -n "${PYTHONPATH:-}" ]; then
  export PYTHONPATH="${REPO_ROOT}/apps/api/src:${PYTHONPATH}"
else
  export PYTHONPATH="${REPO_ROOT}/apps/api/src"
fi

exec "${PYTHON_BIN}" -m alicebot_api.local_server
